#!/bin/bash
QUE="$@"
[[ -z "$@" ]] && read -p "Search " -r QUE 
play()
{
[[ -z "$QUE" ]] && exit
QUE=$(echo "$QUE" | sed 's/[[:space:]]/-/g')
MENU="fzf --no-preview --cycle --header-first --layout=reverse --no-info"
req="$(curl -s "https://streamo-api.herokuapp.com/search/$QUE")" 
selected=$( echo "$req" | jq '.[]' | grep 'title' | sed -e 's/\"title\"\://g' -e 's/\"//g' -e 's/\,//g' | cat -n | $MENU | awk '{print $1}' )
[[ -z "$selected" ]] && exit
id=$( echo "$req" | jq '.[]' | grep 'media_id' | sed -e 's/\"media_id\"\://g' -e 's/\"//g' -e 's/\,//g' | head -n$selected | tail -n1 | sed 's/[[:space:]]//g' )
typeof=$( echo "$req" | jq '.[]' | grep 'media_type' | sed -e 's/\"media_type\"\://g' -e 's/\"//g' -e 's/\,//g' | head -n$selected | tail -n1 | sed -e 's/[[:space:]]//g' -e 's/Movie/m/g' -e 's/Tv/tv/g' )
req="$(curl -s "https://streamo-api.herokuapp.com/$typeof/$id")"
selected=$( echo "$req" | jq | jq '.media_data' | grep 'episode' | sed -e 's/\"episode\"\:/Episode-/g' -e 's/\"//g' -e 's/\,//g' | sed -e 's/[[:space:]]//g' | cat -n | $MENU | awk '{print $1}'  )
[[ -z "$selected" ]] && exit
links=$( echo "$req" | jq | jq '.media_data' | grep 'iframeLink' | sed -e 's/\"iframeLink\"\://g' -e 's/\"//g' -e 's/\,//g' | head -n$selected | tail -n1 | sed -e 's/[[:space:]]//g')
[[ -z "$selected" ]] && exit
id=$(echo "$links" | head -n$selected | tail -n1 | sed 's/[[:space:]]//g' | sed 's/https:\/\/video.moviedata.xyz\/embed\/player.html//g')
id=$(curl -s "https://app.opencdn.co/movie$id" | jq '.fembed.link' | sed 's/"//g' | sed 's/https:\/\/moviepl.xyz\/v//g')
raw=$(curl -s "https://moviepl.xyz/api/source$id" \
  -H 'authority: moviepl.xyz' \
  -H 'accept: */*' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.74 Safari/537.36' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'sec-gpc: 1' \
  -H 'origin: https://moviepl.xyz' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H "referer: https://moviepl.xyz/v$id" \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'dnt: 1' \
  --data-raw 'r=&d=moviepl.xyz' \
  --compressed )
links="$(echo "$raw" |  jq '.data[]' | jq '.file' | sed 's/"//g')"
selected="$(echo "$raw" | jq '.data[]' | jq '.label' | sed 's/"//g' | cat -n | sed 's/^[ \t]*//g' | $MENU | awk '{print $1}')" 
[[ -z "$selected" ]] && exit
lp="$(echo -e "A Play\nB Downlaod" | $MENU | awk '{print $1}')"
case $lp in
  A)
	(nohup mpv --really-quiet "$(echo "$links" | head -n$selected | tail -n1 )" & > /dev/null 2>&1 && disown > /dev/null 2>&1 ) > /dev/null 2>&1 
	play
	;;
  B)
    	org_p=$PWD
	mkdir -p "$HOME/Videos/Streamo/$(echo "$QUE" | sed 's/+/-/g')"
	cd "$HOME/Videos/Streamo/$(echo "$QUE" | sed 's/+/-/g')"
	curl -fL "$(echo "$links" | head -n$selected | tail -n1 )" > "$(echo "$QUE" | sed 's/+/-/g')-EP-$ep-$(date | sed 's/[[:space:]]/-/g').mp4"
	cd $org_p
	exit
	;;
  *)
 	exit
	;;
    esac
} 
play
